name: Deploy to GitHub Pages (Alternative)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Next.js
        run: npm run build
      
      - name: Setup SPA routing for GitHub Pages
        run: |
          # Copy the 404.html to out directory
          cp public/404.html out/404.html
          # Copy .nojekyll to disable Jekyll processing
          cp public/.nojekyll out/.nojekyll
          # Add SPA script to the main index.html
          sed -i 's|</head>|  <script type="text/javascript">\n    // Single Page Apps for GitHub Pages\n    (function(l) {\n      if (l.search[1] === '\''/'\'' ) {\n        var decoded = l.search.slice(1).split('\''&'\'').map(function(s) { \n          return s.replace(/~and~/g, '\''&'\'')\n        }).join('\''?'\'');\n        window.history.replaceState(null, null,\n            l.pathname.slice(0, -1) + decoded + l.hash\n        );\n      }\n    }(window.location))\n  </script>\n</head>|g' out/index.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          force_orphan: true
